### PR TITLE
Add option to hide notification count.

### PR DESCRIPTION
**Pull request by Schroedi**

### CODE REVIEW

**Comment by nls1729** [comment]
I am not sure the option is useful.  I am sure you have reason to believe it is useful and others might find it useful.   My reasons for providing the count is based on the transient nature of most notifications.  Urgency level low and normal notifications are transient.  Only critical level notifications are not.  When the extension is set to "off",  the count alerts the user of hidden notifications.  When the extension is set to "on", the count can also alert the user to hidden notifications that may have been displayed and not seen by the user.

1. I checked the code and found one nit-pick, line 129 in prefs.js is blank and is not needed.

2. Line 53 in prefs.js adds the string, "Show Notification Count".  You need to add translations for the string to files de.po, el.po, es.po, fr.po, and it.po.

If you take care of 1 and 2,  I will merge and update the extension website.

Thanks for your merge request.

**Comment by Schroedi** [comment]
Thanks for your feedback. I get your point. For me, I keep my chats in the notification area. As they always stay there, I would have to remember the number to check if there are new notifications. So the real solution might be to subtract the number of read notifications. Do you know if there is a way to do this? When unread notifications are available, there is a dot next to the clock, so there should be some way.

If you don't mind, I still would like to keep the option to disable the notification count display. For example during presentations, I prefer my desktop to stay clean.

The German translation should be good. The others are based on automatic translations from the internet though. I could try and ask a friend to check the French and Spanish translations, but I don't know anybody from Greece or Italy.

Thanks for the extension and for your time reviewing my request.

**Comment by nls1729** [comment]
"So the real solution might be to subtract the number of read notifications."

While looking into the above,  I found a case where unread notifications can occur and the dot next to the clock is not displayed.  When the count is not shown this can be a problem if the extension is blocking the display of new notifications.  The problem is connected to how the shell queues notifications.  I think if this problem is fixed properly using the extension without displaying a count might be preferred.  Hopefully, I will have a fix by tomorrow.

**Comment by nls1729** [comment]
I have a fix.  I need to do more testing and hopefully get it to you tomorrow.

**Comment by nls1729** [comment]
I cloned your acme-code repo.  I created a patch to handle unseen
notifications.  patch1.patch and notes.txt are attached to this
comment.  If all goes well I will merge your pull request. 

Please remove .txt extension before you attempt to apply patch.

[notes.txt](https://github.com/nls1729/acme-code/files/1014972/notes.txt)


[patch1.patch.txt](https://github.com/nls1729/acme-code/files/1014973/patch1.patch.txt)

**Comment by Schroedi** [comment]
That looks great. I was able to reproduce the issue. Without notification count display, the dot appears with the first notification. With the notification count enabled, the dot only appears with the fourth notification. Is this intended?

I will be away from my PC for the next week. Fee free to directly integrate the changes from this PR and just close it.

**Comment by nls1729** [comment]
"Is this intended?"
Yes, but I have been thinking that showing the dot when the count is enabled and the extension is set to busy.   It seems  a reasonable way for the extension to operate.

Thanks again for your pull request.  I have an email link at  https://nls1729.github.io/index.html.  Please feel free to email me anytime, if you think I can be of help.

**Pull request merged**
