### PR TITLE
Update extension.js

### PR DESCRIPTION
**Pull request by hobbypunk90**
remove most deprecated .actor references and use the ExtensionManager to load the extensions.

### CODE REVIEW

**Comment by hobbypunk90** [comment]
i actually try to understand why the activate function of the SubMenuItem is not called...

**Comment by nls1729** [comment]
I think this relates to your comment, "i actually try to understand why the activate function of the SubMenuItem is not called... ".

GS version 3.34.
From https://github.com/GNOME/gnome-shell/blob/master/js/ui/popupMenu.js line 695-697:

This in PopupMenuBase which is an abstract class and the base for all menu thingies not a registered GObject class.

        } else if (menuItem instanceof PopupSubMenuMenuItem) {
            if (beforeItem == null)
                this.box.add(menuItem.menu.actor);
                
menuItem instance has a menu which is not an actor, it has an actor

... I could be wrong.

**Comment by nls1729** [comment]
I merged it and got your code and then reverted the merge.  I have the code and now understand your comment, "i actually try to understand why the activate function of the SubMenuItem is not called... ".
I don't have time to try and determine what is wrong.

**Comment by nls1729** [comment]
I have looked at the code.  The GS3.34 shell has made changes to extension support that make it impossible to make this extension functional.  Several functions that are required by the extension have been removed.   I think end of support for this extension at GS3.34 is  my only choice.

**Comment by hobbypunk90** [comment]
i got the extension working again.
the only thing: it looks like it don't reload the source of the extension...

**Comment by nls1729** [comment]
I found all the problems with the code.  It is late afternoon here and I need to clean out all the logging from the code.  I will post a patch here as soon as I get time to complete it.

**Comment by nls1729** [comment]
I decided it is best to attach a zip of  the three files that I changed to get the extension working.
The thing I missed and finally noticed was line 107 in extension.js.  

[files.zip](https://github.com/nls1729/acme-code/files/3652032/files.zip)

I also attached a zip of the extension which can be installed.

[extension-reloader@nls1729.zip](https://github.com/nls1729/acme-code/files/3652137/extension-reloader%40nls1729.zip)


Let me know how it goes.

**Pull request merged**
